### ISSUE TITLE
Problem running Start \ main.py 

### ISSUE THREAD

**Issue by Yogevsho** [JorianWoltjer/transcribe-to-premiere#1]
hey. followed the steps for installing, than when im trying to run im getting:

[~] Loading modules...
Traceback (most recent call last):
  File "C:\Users\YogevShoshan\testcaps\AutoCaptions\main.py", line 15, in <module>
    from transcribe import transcribe_to_srt
  File "C:\Users\YogevShoshan\testcaps\AutoCaptions\transcribe.py", line 6, in <module>
    from stable_whisper import load_model, to_srt, transcribe_word_level, finalize_segment_word_ts
ImportError: cannot import name 'to_srt' from 'stable_whisper' (C:\Users\YogevShoshan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_whisper\__init__.py)

will appreciate any help! :)

**Comment by JorianWoltjer** [comment]
Thanks for letting me know!
It looks like the [`stable-ts`](https://github.com/jianfch/stable-ts) library has changed its API by removing the `to_srt` function and generalizing the process (in [`text_output.py`](https://github.com/jianfch/stable-ts/blob/main/stable_whisper/text_output.py)). 

I'll see if I can rewrite it easily to use the new API or if I just have to lock the version to a working one in `requirements.txt`

**Comment by Yogevsho** [comment]
Hey thanks for the quick response! 
and that was my guess after i went over the stable-ts code and couldn’t find any ‘to_srt’ part :)
Is there a way for me to install the previous version of ‘stable-ts’ (the one you got it to work with) and get it to work? 
if so and you could inform me on how to do so, i will appreciate it :)

**Comment by JorianWoltjer** [comment]
The breaking changes seem to be from version 1 to 2, so something like this should work:
```Shell
python -m pip install stable-ts==1
```

**Comment by JorianWoltjer** [comment]
Good news, the new Version 2 of stable-ts has many improvements, including regrouping functions similar to what I had already implemented myself for this tool. That means the code will be a lot simpler, and the results should be better!

I've just got it working with the new version, just doing some testing, and it will probably be done soon.

**Comment by JorianWoltjer** [comment]
Updated version is now live, let me know if you have any issues!

**Comment by Yogevsho** [comment]
My man! Forgot to respond but it works perfectly now, thank u so much! 
a quick question - i saw on stable-ts repo that it’s possible to use faster whisper, would you mind telling me how can i do that here with your repo? :) 
*Maybe even with whisper-jax? 😯

**Comment by JorianWoltjer** [comment]
That looks interesting, I suspect you mean the [`faster-whisper`](https://github.com/guillaumekln/faster-whisper) repository they link from stable-ts? I'll create a new issue to see if this is feasible

**Comment by Yogevsho** [comment]
> That looks interesting, I suspect you mean the [`faster-whisper`](https://github.com/guillaumekln/faster-whisper) repository they link from stable-ts? I'll create a new issue to see if this is feasible

Yes, exactly what i mean :)
Thanks! 🙏
